Avoid time.time() and use time.monotonic().
This code does not work on Adafruit Feather STM32F405 Express because RTC is not implemented (yet?).
'''
        t_start = time.time()
        while time.time() - t_start < timeout:
'''

And I get this kind of error:
'''
  File "pimoroni_ltr559/__init__.py", line 224, in __init__
RuntimeError: RTC is not supported on this board
'''

As this code is just to check for a timeout, it does not need absolute time but only relative time from one call to another.

Not sure if this code is man made or computer generated.